### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by worp1900** [kosz78/wox.plugin.putty#10]
I'd like to use the plugin but there is no documentation on how to do so.

Opening Wox and typing "putty" can start the program, but that can be done without the plugin. 

So how is it used?

**Comment by CWempe** [comment]
I was struggeling with the same.

When you start typing `p` for "putty" you see the entry `pt".

![image](https://user-images.githubusercontent.com/1270359/70134520-8c187d80-1688-11ea-8fb9-09e53d80c8da.png)

So you need to type `pt` to use this plugin.

But it would be great if there was a little documentation for beginners like us. 😄

**Comment by worp1900** [comment]
I see. Thx! Cheers for the info.
I have since stopped using the workflow though.
