### ISSUE TITLE
fails to launch putty session

### ISSUE THREAD

**Issue by timvoet** [kosz78/wox.plugin.putty#5]
whenever i try to launch a putty session ( even a clean one ) i get a Unable to launch, file not found error.  No details as to which file.

When using the pt prefix, it lists all known saved sessions, but fails to launch them

**Comment by RoyJacobs** [comment]
putty.exe needs to be in your PATH

**Comment by timvoet** [comment]
thank you.  I couldn't figure it out, as it would like putty as well as each of my saved profiles, but could not launch.  Also couldn't see any error messages in the log files.
